site_name: DraftPilot Documentation
site_description: AI-powered screenplay editor and story development platform
site_author: Amruth Vithala
site_url: https://draftpilot.com/
repo_name: DraftPilot
repo_url: https://github.com/amruthvvkp/DraftPilot

theme:
  name: material
  logo: meta/logo.jpg
  favicon: meta/favicon.ico

  features:
    - announce.dismiss
    - content.code.copy
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.sections.sticky
    - search.suggest
    - search.highlight
    - navigation.path
    - navigation.indexes
    - content.tabs.link
  font:
    text: Inter
    code: Source Code Pro
  palette:
    - media: "(prefers-color-scheme: light)"
      accent: "#0225AC"
      primary: "#0225AC"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      accent: "#0225AC"
      primary: "#0225AC"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  language: en

markdown_extensions:
  - admonition
  - codehilite
  - md_in_html
  - meta
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
      pygments_lang_class: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.mark
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - tables

plugins:
  - search
  - panzoom:
      full_screen: True
  - autorefs # https://mkdocstrings.github.io/autorefs/
  - mkdocstrings:
      # https://mkdocstrings.github.io/python/usage/
      handlers:
        python:
          import:
            - https://docs.python-requests.org/en/master/objects.inv
          options:
            show_docstring_examples: true
            docstring_style: sphinx
            show_signature: true
            show_docstring_parameters: true
            show_docstring_raises: true
            group_by_category: true
            separate_signature: true
            line_length: 120

watch:
  - README.md

# Extra configuration
extra:
  generator: false # Remove footer from mkdocs material rended pages

nav:
  - Home: index.md
  - Packaging-Guide: packaging-guide.md
