[project]
name = "draftpilot"
version = "0.1.0"
description = "AI-powered screenplay editor and story development platform"
readme = "README.md"
authors = [{ name = "Amruth Vithala", email = "amruthvvkp@gmail.com" }]
requires-python = ">=3.12"
license = { text = "MIT" }
keywords = ["screenplay", "screenwriting", "ai", "storytelling", "film"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: End Users/Desktop",
    "Topic :: Multimedia :: Video",
    "Topic :: Text Editors",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.12",
]
dependencies = ["draftpilot-mcp", "draftpilot-core"]

[tool.uv.sources]
draftpilot-mcp = { workspace = true }
draftpilot-core = { workspace = true }
draftpilot-ui = { workspace = true }

[tool.uv.workspace]
members = ["draftpilot-mcp", "draftpilot-core", "draftpilot-ui"]

[dependency-groups]
docs = [
    "mkdocs>=1.6.1",
    "mkdocs-autorefs>=1.4.2",
    "mkdocs-gen-files>=0.5.0",
    "mkdocs-material>=9.6.17",
    "mkdocs-panzoom-plugin>=0.3.0",
    "mkdocstrings[python]>=0.30.0",
]
ui = [
    "draftpilot-ui"
]

[project.urls]
Homepage = "https://github.com/amruthvvkp/DraftPilot"
# Documentation = "https://draftpilot.dev/docs"
Repository = "https://github.com/amruthvvkp/DraftPilot"
Issues = "https://github.com/amruthvvkp/DraftPilot/issues"
