"""Assist the project-creation wizard with structured story generation."""

import logfire
from pydantic import BaseModel, Field

from draftpilot.core.config import LLMSettings, settings
from draftpilot.core.providers import build_chat_model


class WizardAssistCharacter(BaseModel):
    """Represent one generated character in the project proposal."""

    name: str = Field(min_length=1, max_length=100)
    role: str = Field(default="protagonist", max_length=100)
    description: str = Field(default="", max_length=500)


class WizardAssistRequest(BaseModel):
    """Specify creative constraints to bootstrap a project brief."""

    prompt: str = Field(min_length=1, max_length=2000)
    target_format: str = Field(default="feature", max_length=50)
    primary_language: str = Field(default="English", max_length=50)
    genre_preference: str | None = Field(default=None, max_length=50)


class WizardAssistResponse(BaseModel):
    """Return structured project creation fields generated by an agent."""

    title: str
    logline: str
    description: str
    story_outline: str
    genres: list[str] = Field(default_factory=list)
    target_audience: str = "General cinematic audience"
    characters: list[WizardAssistCharacter] = Field(default_factory=list)
    visual_style: str = "Atmospheric, naturalistic lighting with high textural contrast."
    camera_type: str = "Digital"
    screening_type: str = "flat_1_85"
    primary_language: str = "English"
    format: str = "feature"


def fallback_wizard_assist(request: WizardAssistRequest) -> WizardAssistResponse:
    """Derive deterministic structured story fields when LLM is unavailable."""
    raw = request.prompt.strip()
    words = raw.split()
    first_few = " ".join(words[:4]).title() if words else "Untitled Project"
    clean_title = "".join(c for c in first_few if c.isalnum() or c.isspace()).strip() or "Untitled Project"

    lowered = raw.lower()
    detected_genres: list[str] = []
    if request.genre_preference:
        detected_genres.append(request.genre_preference)

    genre_keywords: list[tuple[str, list[str]]] = [
        ("Sci-Fi", ["future", "space", "alien", "robot", "cyber", "signal", "quantum"]),
        ("Horror", ["haunted", "ghost", "monster", "demon", "blood", "curse", "terror"]),
        ("Mystery", ["detective", "murder", "clue", "investigate", "secret", "disappearance"]),
        ("Thriller", ["conspiracy", "escape", "hunt", "chase", "danger", "race against"]),
        ("Romance", ["love", "romance", "passion", "lover", "heart", "wedding"]),
        ("Comedy", ["funny", "laugh", "hilarious", "parody", "satire"]),
    ]
    for genre, terms in genre_keywords:
        if any(term in lowered for term in terms) and genre not in detected_genres:
            detected_genres.append(genre)

    if not detected_genres:
        detected_genres = ["Drama"]

    logline = (
        raw if raw.endswith((".", "!", "?"))
        else f"{raw}."
    )

    description = (
        f"A character-driven {request.target_format} exploring the consequences of {raw.lower()}."
    )

    story_outline = (
        "Act I: We establish our protagonist's fragile world before the inciting catalyst disrupts everything.\n"
        "Act II: Deepening conflict forces our protagonist into unfamiliar territory with rising stakes.\n"
        "Act III: A climactic confrontation forces a transformative choice and resolves the story."
    )

    characters = [
        WizardAssistCharacter(
            name="Protagonist",
            role="lead",
            description="Driven by conviction, yet burdened by an unresolved vulnerability.",
        ),
        WizardAssistCharacter(
            name="Counterpart",
            role="catalyst",
            description="Challenges the protagonist's worldview and forces the pivotal choice.",
        ),
    ]

    return WizardAssistResponse(
        title=clean_title,
        logline=logline,
        description=description,
        story_outline=story_outline,
        genres=detected_genres[:3],
        target_audience="General cinematic audience seeking thought-provoking narrative.",
        characters=characters,
        visual_style="Grounded, atmospheric cinematography with tactile world texture.",
        camera_type="Digital",
        screening_type="flat_1_85",
        primary_language=request.primary_language,
        format=request.target_format,
    )


async def generate_wizard_assist(
    request: WizardAssistRequest, llm_settings: LLMSettings | None = None
) -> WizardAssistResponse:
    """Generate structured project wizard fields using configured LLM or fallback."""
    config = llm_settings or settings.llm
    if not config.enabled:
        return fallback_wizard_assist(request)
    try:
        from pydantic_ai import Agent, NativeOutput

        model, _name = await build_chat_model(config)
        agent: Agent[None, WizardAssistResponse] = Agent(
            model,
            output_type=NativeOutput(WizardAssistResponse),
            system_prompt=(
                "You are an expert screenplay development executive for DraftPilot. "
                "From the writer's premise or creative spark, propose an evocative, structured project brief. "
                "Provide a compelling title, a single-sentence active logline, a clear three-act outline, "
                "appropriate genres, key character sketches, and visual style notes."
            ),
        )
        result = await agent.run(
            f"Premise: {request.prompt}\n"
            f"Target format: {request.target_format}\n"
            f"Primary language: {request.primary_language}\n"
            f"Preferred genre: {request.genre_preference or 'None specified'}"
        )
        output = result.output
        if isinstance(output, WizardAssistResponse):
            return output
        if isinstance(output, dict):
            return WizardAssistResponse.model_validate(output)
        return fallback_wizard_assist(request)
    except Exception as exc:  # noqa: BLE001 - any provider failure degrades to the heuristic brief
        logfire.warning("Wizard assist fell back to the heuristic brief: {exc}", exc=str(exc))
        return fallback_wizard_assist(request)
