"""initial schema: project, screenplay, scene

Revision ID: 121586f96c09
Revises: 
Create Date: 2026-06-24 15:30:40.737416
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '121586f96c09'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('logline', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('genre', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_title'), 'project', ['title'], unique=False)
    op.create_table('screenplay',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('format', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_screenplay_project_id'), 'screenplay', ['project_id'], unique=False)
    op.create_index(op.f('ix_screenplay_title'), 'screenplay', ['title'], unique=False)
    op.create_table('scene',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('heading', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('screenplay_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['screenplay_id'], ['screenplay.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scene_position'), 'scene', ['position'], unique=False)
    op.create_index(op.f('ix_scene_screenplay_id'), 'scene', ['screenplay_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scene_screenplay_id'), table_name='scene')
    op.drop_index(op.f('ix_scene_position'), table_name='scene')
    op.drop_table('scene')
    op.drop_index(op.f('ix_screenplay_title'), table_name='screenplay')
    op.drop_index(op.f('ix_screenplay_project_id'), table_name='screenplay')
    op.drop_table('screenplay')
    op.drop_index(op.f('ix_project_title'), table_name='project')
    op.drop_table('project')
    # ### end Alembic commands ###
