"""Generate docs/dev/http-api.md from the app's OpenAPI schema (``--check`` fails when it is stale)."""

import sys
from collections import defaultdict
from pathlib import Path
from typing import Any

from draftpilot.api.app import create_app

TARGET = Path(__file__).resolve().parents[1] / "docs" / "dev" / "http-api.md"
HEADER = """# HTTP API reference

Every endpoint lives under `/api/v1`. Except for the `auth` endpoints, all of them need the
`API__TOKEN` bearer token or the studio's session cookie. The live, interactive schema is at
`/docs` and `/openapi.json` on a running web process. This page is generated by
`scripts/gen_http_api_docs.py`; don't edit it by hand.
"""


def _schema_name(schema: dict[str, Any] | None) -> str:
    """Return a short name for a request or response schema."""
    if not schema:
        return ""
    if "$ref" in schema:
        return f"`{schema['$ref'].rsplit('/', 1)[-1]}`"
    if schema.get("type") == "array" and "items" in schema:
        inner = _schema_name(schema["items"])
        return f"list of {inner}" if inner else "list"
    return f"`{schema.get('type', 'object')}`" if schema.get("type") else ""


def render() -> str:
    """Render the reference: one table per tag, one row per operation."""
    spec = create_app().openapi()
    by_tag: dict[str, list[tuple[str, str, dict[str, Any]]]] = defaultdict(list)
    for path, operations in spec["paths"].items():
        if not path.startswith("/api/v1"):
            continue
        for method, operation in operations.items():
            by_tag[(operation.get("tags") or ["other"])[0]].append((method.upper(), path.removeprefix("/api/v1"), operation))
    lines = [HEADER]
    for tag in sorted(by_tag):
        lines += [f"## {tag}", "", "| Method | Path | What it does | Body | Returns |", "|---|---|---|---|---|"]
        for method, path, operation in sorted(by_tag[tag], key=lambda item: (item[1], item[0])):
            summary = (operation.get("description") or operation.get("summary") or "").strip().splitlines()[0] if (operation.get("description") or operation.get("summary")) else ""
            body = _schema_name(operation.get("requestBody", {}).get("content", {}).get("application/json", {}).get("schema"))
            responses = operation.get("responses", {})
            success = next((code for code in responses if code.startswith("2")), "")
            returns = _schema_name(responses.get(success, {}).get("content", {}).get("application/json", {}).get("schema")) if success else ""
            lines.append(f"| `{method}` | `{path}` | {summary.replace('|', '\\|')} | {body} | {success} {returns}".rstrip() + " |")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    """Write the reference, or with ``--check`` exit non-zero if it is out of date."""
    content = render()
    if "--check" in sys.argv:
        if not TARGET.exists() or TARGET.read_text() != content:
            sys.exit("docs/dev/http-api.md is stale: run `uv run python scripts/gen_http_api_docs.py`")
        return
    TARGET.write_text(content)
    print(f"wrote {TARGET}")


if __name__ == "__main__":
    main()
